import 'shared_prefs.dart';
import 'dart:math';

class Words {

  final _random = new Random();
  SharedPref sharedPref = SharedPref();

  // List of words by languages
  Map words = {
  // Croatian words
  'croatian': [
    'Abortirati',
    'Administrator',
    'Adresa',
    'Adolescent',
    'Advent',
    'Advokat',
    'Aerodrom',
    'Afera',
    'Afrika',
    'Agencija',
    'Azija',
    'Agresivan',
    'Agrum',
    'Akademski',
    'Akcent',
    'Akcijski',
    'Akna',
    'Akord',
    'Akrobacije',
    'Aktivna',
    'Aktiviranje',
    'Akumulacijski',
    'Akustika',
    'Akuzativ',
    'Akvarij',
    'Alarmi',
    'Albino',
    'Aleja',
    'Alergična',
    'Alge',
    'Alibi',
    'Alkemičar',
    'Alkohol',
    'Alternativa',
    'Animacije',
    'Anketa',
    'Anoniman',
    'Antena',
    'Antibiotici',
    'Apoteka',
    'Apsolutno',
    'Babaroga',
    'Baka',
    'Brat',
    'Bacanje',
    'Bačva',
    'Birati',
    'Badava',
    'Bager',
    'Broj',
    'Bahata',
    'Biljka',
    'Bajka',
    'Badem',
    'Brokula',
    'Bajram',
    'Bakalar',
    'Baklje',
    'Bakteriologija',
    'Balans',
    'Brbljavac',
    'Bašćanska ploča',
    'Balkon',
    'Banda',
    'Bankar',
    'Caklina',
    'Carevi',
    'Carevo',
    'Carinik',
    'CD',
    'Cedulja',
    'Cement',
    'Celzij',
    'Cendranje',
    'Centrirati',
    'Čađa',
    'Čaj',
    'Čarapa',
    'Čavrljanje',
    'Čekanje',
    'Čestica',
    'Ćakulati',
    'Ćevapčić',
    'Ćudljiv',
    'Ćirilica',
    'Dabar',
    'Dahtati',
    'Dizanje utega',
    'Dalekovidan',
    'Dalmatinski naglasak',
    'Daljina',
    'Dan',
    'Dvorski',
    'Današnjica',
    'Dan danas',
    'Darovnica',
    'Dašak zraka',
    'Davanje',
    'Datoteke',
    'Davež',
    'Dekan',
    'Deklinacija pridjeva',
    'Demon',
    'Desetogodišnjakinja',
    'Desetorica',
    'Desni',
    'Desničar',
    'Didaskalije',
    'Danska',
    'Dubrovnik',
    'Domoljub',
    'Dijabetičar',
    'Dijafragma',
    'Dijagnostika',
    'Dom',
    'Dika',
    'Datulje',
    'Darovi',
    'Dug',
    'Dama',
    'Dužina',
    'Debelo',
    'Duplo',
    'Diploma',
    'Doktor',
    'Džentlmen',
    'Džep',
    'Džungla',
    'Đon',
    'Đački pokaz',
    'Đurđa',
    'Efekt',
    'Egoističan',
    'Egocentričan',
    'Energija',
    'Egzistencija',
    'Ekipa',
    'Emoji',
    'Ekonomičan',
    'Ekologija',
    'Ekvator',
    'Elastričan',
    'Elegantna haljina',
    'Elektromotor',
    'Fabula',
    'Fakultativno',
    'Fascikl',
    'Familija',
    'Fantazija',
    'Fora',
    'Fiktivan',
    'Faraon',
    'Farma',
    'Farmaceutkinja',
    'Fascinantan',
    'Fasada',
    'Faza',
    'Federalizam',
    'Feferon',
    'Feminizam',
    'Gaće',
    'Glančanje',
    'Gadljiv',
    'Gajde',
    'Galamiti',
    'Galerija',
    'Grom',
    'Golub',
    'Galeb',
    'Galija',
    'Galijot',
    'Garancija',
    'Garava',
    'Garažna vrata',
    'Gurnuti',
    'Gasiti vatru',
    'Hladno',
    'Haiku',
    'Hodočašće',
    'Hajduk',
    'Hakirati igricu',
    'Haluciniranje',
    'Hipodrom',
    'Himna',
    'Hangar',
    'Hanuka',
    'Histerija',
    'Harfa',
  ],
  // English words
  'english': [
    'Abortion',
    'Administrator',
    'Address',
    'Adolescent',
    'Advent',
    'Lawyer',
    'Airport',
    'Affair',
    'Africa',
    'Agency',
    'Asia',
    'Aggressive',
    'Citrus',
    'Academic',
    'Accent',
    'Action',
    'Acne',
    'Chord',
    'Acrobatics',
    'Active',
    'Activation',
    'Accumulation',
    'Acoustics',
    'Accusative',
    'Aquarium',
    'Alarms',
    'Albino',
    'Alley',
    'Allergic',
    'Seaweed',
    'Alibi',
    'Alchemist',
    'Alcohol',
    'Alternative',
    'Animations',
    'Poll',
    'Anonymous',
    'Antenna',
    'Antibiotics',
    'Pharmacy',
    'Absolutely',
    'Babaroga',
    'Grandmother',
    'Brother',
    'Throwing',
    'Barrel',
    'Choose',
    'Free',
    'Excavator',
    'Number',
    'Bahata',
    'Plant',
    'Fairytale',
    'Almond',
    'Broccoli',
    'Eid',
    'Cod',
    'Torches',
    'Bacteriology',
    'Balance',
    'Chatterbox',
    'Balcony',
    'Gang',
    'Banker',
    'Enamel',
    'Kings',
    'Customs officer',
    'CD',
    'Scrip',
    'Cement',
    'Celsius',
    'Straining',
    'Center',
    'Soot',
    'Tea',
    'Sock',
    'Chat',
    'Waiting',
    'Particle',
    'Moody',
    'Cyrillic',
    'Beaver',
    'Pant',
    'Weightlifting',
    'Farsighted',
    'Distance',
    'Day',
    'Courtly',
    'Today',
    'Up to this day',
    'Grant',
    'A breath of air',
    'Giving',
    'Files',
    'Crush',
    'Dean',
    'Declension of adjectives',
    'Demon',
    'A ten-year-old',
    'Ten',
    'Right',
    'Rightist',
    'Didascalia',
    'Denmark',
    'Dubrovnik',
    'Patriot',
    'Diabetic',
    'Diaphragm',
    'Diagnostic',
    'Home',
    'Pride',
    'Dates',
    'Gifts',
    'Debt',
    'Lady',
    'Length',
    'Thick',
    'Twice',
    'Diploma',
    'Doctor',
    'Gentleman',
    'Pocket',
    'Jungle',
    'Sole',
    'Student show',
    'Effect',
    'Egoistic',
    'Egocentric',
    'Energy',
    'Existence',
    'Team',
    'Emoji',
    'Economical',
    'Ecology',
    'Equator',
    'Elastic',
    'Elegant dress',
    'Electromotor',
    'Fable',
    'Optional',
    'Folder',
    'Family',
    'Fantasy',
    'Handicap',
    'Fictitious',
    'Pharaoh',
    'Farm',
    'Pharmacist',
    'Fascinating',
    'Facade',
    'Phase',
    'Federalism',
    'Pepperoni',
    'Feminism',
    'Underpants',
    'Polishing',
    'Squeamish',
    'Bagpipes',
    'Noise',
    'Gallery',
    'Thunder',
    'Pigeon',
    'Seagull',
    'Gaul',
    'Galliots',
    'Guarantee',
    'Garava',
    'Garage door',
    'Push',
    'Extinguish the fire',
    "It's cold",
    'Haiku',
    'Pilgrimage',
    'Hack the game',
    'Hallucination',
    'Hippodrome',
    'Anthem',
    'Hangar',
    'Hanukkah',
    'Hysteria',
  ]};

  // Helper list of words
  Map wordsHelper = {'english': List<String>(), 'croatian': List<String>()};

  String language = "";

  nextWord() async {
    // Get language from shared prefs
    language = await sharedPref.readLanguage();

    // Get one word with random index
    String word = words[language][_random.nextInt(words[language].length)];

    // If helper list is full clear it
    if (wordsHelper[language].length >= words[language].length)
      wordsHelper[language].clear();

    // If helper list already contains word call function again
    if (wordsHelper[language].contains(word))
      return nextWord();
    else {
      wordsHelper[language].add(word); // Add word to helper list
      return word; // Return word
    }
  }

  clearHelper() async {
    // Clear helper list
    wordsHelper.clear();
  }
}